# Generated by Django 4.1.3 on 2022-11-23 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_found_post_lost_post_delete_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Found_Post",
        ),
    ]
