# Generated by Django 4.1.3 on 2022-11-26 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_delete_found_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lost_post",
            old_name="descriptipon",
            new_name="description",
        ),
    ]
